name: Build Bedrock
on: [push, pull_request]

env:
  REPO_URL: https://github.com/cterxn/bedrocklinux-userland.git
  REPO_BRANCH: master
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /bedrock
        sudo chown $USER:$GROUPS 
    - name: Clone source code
      working-directory: /bedrock
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH bedrock
        ln -sf /bedrock/bedrock $GITHUB_WORKSPACE/bedrock
    - name: Make
      working-directory: /bedrock
      run: |
        make -j3  GPGID=83c1923eb62f21bee688c71d8d15189961bac593
